### ISSUE TITLE
ITACA: Interference and Traffic aware Channel Assignmnet

### ISSUE THREAD

**Issue by hafeez2010** [wing-project/wing-project.github.io#1]
When I try to access link below 
 http://www.wing-project.org/directions:channel_assignment/ for NS2 simulation code I get error file not found. Please guide where I can find material.

Hafeez
hafeez.admc@gmail.com

**Comment by rriggio** [comment]
This issue tracker is for issues related with the real implementation of wing, not for bug reports on the website. The NS2 code is not available anymore.
